### PR TITLE
Create 9 disks to be used for integration testing

### PR DESCRIPTION
**Pull request by johnsonw**
Signed-off-by: Will Johnson <william.c.johnson@intel.com>

### CODE REVIEW

**Comment by jgrund** [comment]
Do you need to update snapshots?

**Comment by johnsonw** [comment]
yes, currently updating existing snapshots.

**Comment by jgrund** [comment]
Can we make this 100 disks instead?

**Comment by johnsonw** [comment]
👍

**Comment by johnsonw** [comment]
Attempted to use 100 disks, which will use 100 ports and received a message indicating that it could use a maximum of 30 ports. I attempted to increase the ports to 100 using vboxmanage and received the following error:
```
Command: ["storagectl", "5202d2e3-1284-4653-950e-729f8bd73c14", "--name", "SATA Controller", "--portcount", "100"]

Stderr: VBoxManage: error: Invalid port count: 100 (must be in range [1, 30])
```
Given this, we will have a total of 30 disks.

**Pull request merged**
